//! document_classifier_agent — deterministic golden gate (CI-blocking).
//!
//! per `attune/CLAUDE.md` §「Agent 验证铁律」:
//!   - deterministic agent → required pass rate **1.00**
//!   - ground truth **independent** of `agent.run()` (every case's `expected.*`
//!     is hand-curated by reviewer review; not auto-generated by the agent)
//!   - 6-class coverage floor:
//!       * Golden case ≥ 10 + 1 sentinel ........... 11 in this dir (01..11)
//!       * Property tests ≥ 3 ...................... `document_classifier_proptests.rs`
//!       * Boundary `#[test]` ≥ 5 .................. lib unit tests + this gate's boundary mod
//!       * Error case ≥ 3 .......................... `error/` subdir (3 files)
//!       * Integration E2E ≥ 1 ..................... `document_classifier_agent_integration.rs`
//!       * Regression fixture ...................... 11-sentinel-regression.yaml

use std::collections::BTreeSet;
use std::path::{Path, PathBuf};

use attune_core::agents::document_classifier::{run, DocumentInput};
use serde::Deserialize;

// ── YAML schema (mirrors the golden file shape) ─────────────────────────────

#[derive(Debug, Deserialize)]
struct GoldenCase {
    id: String,
    #[serde(default)]
    #[allow(dead_code)]
    description: String,
    #[serde(default)]
    inputs: Vec<GoldenInput>,
    expected: GoldenExpected,
    #[serde(default)]
    reviewer: Reviewer,
}

#[derive(Debug, Deserialize)]
struct GoldenInput {
    file: String,
    text: String,
}

#[derive(Debug, Deserialize, Default)]
struct GoldenExpected {
    #[serde(default)]
    classified_count: Option<usize>,
    #[serde(default)]
    per_doc: Vec<GoldenPerDoc>,
    #[serde(default)]
    kind_summary_keys: Vec<String>,
    #[serde(default)]
    kind_summary_total: Option<usize>,
    #[serde(default)]
    overall_confidence: Option<f64>,
    #[serde(default)]
    overall_confidence_min: Option<f64>,
    #[serde(default)]
    overall_confidence_max: Option<f64>,
    #[serde(default)]
    missing_evidence_min: Option<usize>,
    #[serde(default)]
    missing_evidence_count: Option<usize>,
    #[serde(default)]
    followups_min: Option<usize>,
    #[serde(default)]
    followup_must_contain: Option<String>,
    #[serde(default)]
    red_lines_count: Option<usize>,
}

#[derive(Debug, Deserialize, Default)]
struct GoldenPerDoc {
    file: String,
    #[serde(default)]
    kind: Option<String>,
    #[serde(default)]
    confidence_min: Option<f64>,
    #[serde(default)]
    confidence_max: Option<f64>,
    #[serde(default)]
    keywords_must_contain: Vec<String>,
    #[serde(default)]
    entities: Option<GoldenEntities>,
}

#[derive(Debug, Deserialize, Default)]
struct GoldenEntities {
    #[serde(default)]
    persons_min: Option<usize>,
    #[serde(default)]
    dates_min: Option<usize>,
    #[serde(default)]
    amounts_min: Option<usize>,
    #[serde(default)]
    locations_min: Option<usize>,
}

#[derive(Debug, Deserialize, Default)]
struct Reviewer {
    #[serde(default)]
    approved: bool,
    #[serde(default)]
    #[allow(dead_code)]
    notes: String,
}

// ── Loader ──────────────────────────────────────────────────────────────────

fn golden_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("golden")
        .join("document_classifier")
}

fn load_cases(dir: &Path) -> Vec<(String, GoldenCase)> {
    let mut out = Vec::new();
    let entries = std::fs::read_dir(dir).unwrap_or_else(|e| {
        panic!("read_dir({}): {}", dir.display(), e)
    });
    for ent in entries {
        let ent = ent.unwrap();
        let path = ent.path();
        if path.extension().and_then(|s| s.to_str()) != Some("yaml") {
            continue;
        }
        let text = std::fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("read {}: {}", path.display(), e));
        let case: GoldenCase = serde_yaml::from_str(&text)
            .unwrap_or_else(|e| panic!("parse {}: {}", path.display(), e));
        out.push((path.file_name().unwrap().to_string_lossy().into_owned(), case));
    }
    out.sort_by(|a, b| a.0.cmp(&b.0));
    out
}

// ── Driver ──────────────────────────────────────────────────────────────────

fn run_case(case: &GoldenCase) -> attune_core::agents::AgentOutput<
    attune_core::agents::document_classifier::ClassificationOutput,
> {
    let docs: Vec<DocumentInput<'_>> = case
        .inputs
        .iter()
        .map(|i| DocumentInput { file: i.file.as_str(), text: i.text.as_str() })
        .collect();
    run(&docs)
}

fn assert_case(name: &str, case: &GoldenCase) {
    if !case.reviewer.approved {
        eprintln!("[skip] {} — reviewer.approved=false", name);
        return;
    }
    let out = run_case(case);
    let exp = &case.expected;

    if let Some(n) = exp.classified_count {
        assert_eq!(
            out.computation.classified.len(),
            n,
            "{}: classified_count expected {}, got {}",
            name, n, out.computation.classified.len()
        );
    }

    // overall confidence
    if let Some(c) = exp.overall_confidence {
        let diff = (out.confidence - c).abs();
        assert!(diff < 1e-9, "{}: overall_confidence expected {}, got {}", name, c, out.confidence);
    }
    if let Some(c) = exp.overall_confidence_min {
        assert!(out.confidence >= c, "{}: overall_confidence_min {}, got {}", name, c, out.confidence);
    }
    if let Some(c) = exp.overall_confidence_max {
        assert!(out.confidence <= c, "{}: overall_confidence_max {}, got {}", name, c, out.confidence);
    }

    // red_lines
    if let Some(n) = exp.red_lines_count {
        assert_eq!(
            out.red_lines_violated.len(),
            n,
            "{}: red_lines expected {}, got {:?}",
            name, n, out.red_lines_violated
        );
    }

    // missing_evidence
    if let Some(n) = exp.missing_evidence_count {
        assert_eq!(
            out.missing_evidence.len(),
            n,
            "{}: missing_evidence_count expected {}, got {:?}",
            name, n, out.missing_evidence
        );
    }
    if let Some(n) = exp.missing_evidence_min {
        assert!(
            out.missing_evidence.len() >= n,
            "{}: missing_evidence_min {}, got {} {:?}",
            name, n, out.missing_evidence.len(), out.missing_evidence
        );
    }
    if let Some(n) = exp.followups_min {
        assert!(
            out.followups.len() >= n,
            "{}: followups_min {}, got {} {:?}",
            name, n, out.followups.len(), out.followups
        );
    }
    if let Some(s) = &exp.followup_must_contain {
        assert!(
            out.followups.iter().any(|f| f.contains(s)),
            "{}: followups must contain '{}', got {:?}",
            name, s, out.followups
        );
    }

    // kind_summary
    if !exp.kind_summary_keys.is_empty() {
        let got_keys: BTreeSet<&str> = out
            .computation
            .kind_summary
            .keys()
            .map(|s| s.as_str())
            .collect();
        for k in &exp.kind_summary_keys {
            assert!(
                got_keys.contains(k.as_str()),
                "{}: kind_summary must contain key '{}', got {:?}",
                name, k, got_keys
            );
        }
    }
    if let Some(total) = exp.kind_summary_total {
        let sum: usize = out.computation.kind_summary.values().sum();
        assert_eq!(sum, total, "{}: kind_summary_total expected {}, got {}", name, total, sum);
    }

    // per_doc
    for exp_doc in &exp.per_doc {
        let got = out
            .computation
            .classified
            .iter()
            .find(|c| c.file == exp_doc.file)
            .unwrap_or_else(|| panic!("{}: file '{}' not found in classified", name, exp_doc.file));

        if let Some(kind) = &exp_doc.kind {
            assert_eq!(&got.kind, kind, "{}: file {} kind expected {}, got {}", name, got.file, kind, got.kind);
        }
        if let Some(c) = exp_doc.confidence_min {
            assert!(
                got.confidence >= c,
                "{}: file {} confidence_min {}, got {}",
                name, got.file, c, got.confidence
            );
        }
        if let Some(c) = exp_doc.confidence_max {
            assert!(
                got.confidence <= c,
                "{}: file {} confidence_max {}, got {}",
                name, got.file, c, got.confidence
            );
        }
        for kw in &exp_doc.keywords_must_contain {
            assert!(
                got.matched_keywords.iter().any(|k| k.contains(kw)),
                "{}: file {} matched_keywords must contain '{}', got {:?}",
                name, got.file, kw, got.matched_keywords
            );
        }
        if let Some(ents) = &exp_doc.entities {
            if let Some(n) = ents.persons_min {
                assert!(
                    got.entities.persons.len() >= n,
                    "{}: file {} entities.persons_min {}, got {} {:?}",
                    name, got.file, n, got.entities.persons.len(), got.entities.persons
                );
            }
            if let Some(n) = ents.dates_min {
                assert!(
                    got.entities.dates.len() >= n,
                    "{}: file {} entities.dates_min {}, got {} {:?}",
                    name, got.file, n, got.entities.dates.len(), got.entities.dates
                );
            }
            if let Some(n) = ents.amounts_min {
                assert!(
                    got.entities.amounts.len() >= n,
                    "{}: file {} entities.amounts_min {}, got {}",
                    name, got.file, n, got.entities.amounts.len()
                );
            }
            if let Some(n) = ents.locations_min {
                assert!(
                    got.entities.locations.len() >= n,
                    "{}: file {} entities.locations_min {}, got {} {:?}",
                    name, got.file, n, got.entities.locations.len(), got.entities.locations
                );
            }
        }
    }
}

// ── Tests ───────────────────────────────────────────────────────────────────

#[test]
fn document_classifier_golden_gate() {
    let dir = golden_dir();
    let cases = load_cases(&dir);
    assert!(
        cases.len() >= 11,
        "golden floor: 10 real cases + 1 sentinel, got {}",
        cases.len()
    );
    let approved = cases.iter().filter(|(_, c)| c.reviewer.approved).count();
    assert!(approved >= 10, "approved cases ≥ 10, got {}", approved);

    let mut sentinel_seen = false;
    for (name, case) in &cases {
        assert_case(name, case);
        if case.id.contains("sentinel") {
            sentinel_seen = true;
        }
    }
    assert!(sentinel_seen, "11-sentinel-regression.yaml must exist and run");
}

#[test]
fn document_classifier_error_cases() {
    let dir = golden_dir().join("error");
    let cases = load_cases(&dir);
    assert!(cases.len() >= 3, "error case floor: 3, got {}", cases.len());
    for (name, case) in &cases {
        assert_case(name, case);
    }
}
