//! Office / container format extraction tests (axis A — formats).
//!
//! Dimension owner: §2.6 matrix axis A (格式) for the OFFICE corpus —
//! docx / xlsx / pptx / epub / rtf / csv. Each format → `parser::parse_bytes`
//! returns the KNOWN text (we assert the marker tokens, incl. mixed CN+EN).
//!
//! Fixtures are byte-deterministic, committed under `tests/fixtures/office/`
//! and (re)generated by the committed `scripts/gen-office-fixtures.py`
//! (run `python3 scripts/gen-office-fixtures.py` to regenerate). Each benign
//! fixture carries a unique `ATTUNE_<FMT>_MARKER` token plus ≥1 CN+EN mixed
//! string so we prove both extraction and unicode round-trip.
//!
//! The companion adversarial suite is `office_adversarial_test.rs`.

use std::path::PathBuf;

use attune_core::parser::parse_bytes;

fn office_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/office")
}

fn fixture(name: &str) -> Vec<u8> {
    let p = office_dir().join(name);
    std::fs::read(&p).unwrap_or_else(|e| {
        panic!(
            "missing office fixture {} at {} ({e}); run `python3 scripts/gen-office-fixtures.py`",
            name,
            p.display()
        )
    })
}

// ── DOCX (zip + word/document.xml) ──────────────────────────────────────────

#[test]
fn docx_extracts_known_text_cn_en() {
    let (title, content) = parse_bytes(&fixture("known.docx"), "known.docx").expect("docx must parse");
    assert!(
        content.contains("ATTUNE_DOCX_MARKER"),
        "docx marker missing: title={title:?} content={content:?}"
    );
    assert!(content.contains("Hello World"), "docx EN text missing: {content:?}");
    assert!(content.contains("你好世界"), "docx CN text missing: {content:?}");
}

// ── XLSX (calamine workbook) ────────────────────────────────────────────────

#[test]
fn xlsx_extracts_known_cells_cn_en() {
    let (_title, content) = parse_bytes(&fixture("known.xlsx"), "known.xlsx").expect("xlsx must parse");
    assert!(content.contains("ATTUNE_XLSX_MARKER"), "xlsx marker missing: {content:?}");
    assert!(content.contains("Alice"), "xlsx EN cell missing: {content:?}");
    assert!(content.contains("爱丽丝"), "xlsx CN cell missing: {content:?}");
    assert!(content.contains("北京"), "xlsx CN city missing: {content:?}");
}

// ── PPTX (zip + ppt/slides/slideN.xml) ──────────────────────────────────────

#[test]
fn pptx_extracts_all_slides_in_order_cn_en() {
    let (_title, content) = parse_bytes(&fixture("known.pptx"), "known.pptx").expect("pptx must parse");
    assert!(content.contains("ATTUNE_PPTX_S1"), "pptx slide1 marker missing: {content:?}");
    assert!(content.contains("ATTUNE_PPTX_S2"), "pptx slide2 marker missing: {content:?}");
    assert!(content.contains("第一页"), "pptx CN slide1 missing: {content:?}");
    assert!(content.contains("第二页"), "pptx CN slide2 missing: {content:?}");
    // slide order preserved
    let p1 = content.find("ATTUNE_PPTX_S1").unwrap();
    let p2 = content.find("ATTUNE_PPTX_S2").unwrap();
    assert!(p1 < p2, "slides must be in order (slide1 before slide2): {content:?}");
}

// ── EPUB (zip + *.xhtml) ────────────────────────────────────────────────────

#[test]
fn epub_extracts_chapter_text_cn_en() {
    let (_title, content) = parse_bytes(&fixture("known.epub"), "known.epub").expect("epub must parse");
    assert!(content.contains("ATTUNE_EPUB_MARKER"), "epub marker missing: {content:?}");
    assert!(content.contains("EPUB Chapter"), "epub EN text missing: {content:?}");
    assert!(content.contains("章节"), "epub CN text missing: {content:?}");
}

// ── RTF (plain text control-word stripper) ──────────────────────────────────

#[test]
fn rtf_extracts_known_text() {
    let (_title, content) = parse_bytes(&fixture("known.rtf"), "known.rtf").expect("rtf must parse");
    assert!(content.contains("ATTUNE_RTF_MARKER"), "rtf marker missing: {content:?}");
    assert!(content.contains("Hello RTF"), "rtf EN text missing: {content:?}");
    // \'e9 hex escape → 'é' (Latin-1); control words (\f0, \pard) stripped.
    assert!(!content.contains("\\pard"), "rtf control words must be stripped: {content:?}");
}

// ── CSV (passthrough text) ──────────────────────────────────────────────────

#[test]
fn csv_passthrough_cn_en() {
    let (_title, content) = parse_bytes(&fixture("known.csv"), "known.csv").expect("csv must parse");
    assert!(content.contains("ATTUNE_CSV_MARKER"), "csv marker missing: {content:?}");
    assert!(content.contains("Alice"), "csv EN cell missing: {content:?}");
    assert!(content.contains("城市"), "csv CN header missing: {content:?}");
    assert!(content.contains("北京"), "csv CN value missing: {content:?}");
}

// ── format dispatch sanity: every office ext routes to a non-text parser ─────

#[test]
fn office_formats_all_parse_nonempty() {
    for (name, marker) in [
        ("known.docx", "ATTUNE_DOCX_MARKER"),
        ("known.xlsx", "ATTUNE_XLSX_MARKER"),
        ("known.pptx", "ATTUNE_PPTX_S1"),
        ("known.epub", "ATTUNE_EPUB_MARKER"),
        ("known.rtf", "ATTUNE_RTF_MARKER"),
        ("known.csv", "ATTUNE_CSV_MARKER"),
    ] {
        let (_t, content) = parse_bytes(&fixture(name), name)
            .unwrap_or_else(|e| panic!("{name} must parse: {e}"));
        assert!(!content.trim().is_empty(), "{name} produced empty content");
        assert!(content.contains(marker), "{name} missing marker {marker}: {content:?}");
    }
}
