//! Office / container ADVERSARIAL tests — the P0 security dimension.
//!
//! Dimension owner: §2.6 matrix axis C (鲁棒 6 类) → the OFFICE ZIP/XML
//! adversarial gap (解压炸弹 / entry 路径穿越 / billion-laughs XXE / 超大单条目).
//! docx/xlsx/pptx/epub are ZIP+XML containers parsed from UNTRUSTED uploads, so a
//! crafted file must never hang, OOM, or escape the filesystem.
//!
//! "证明它会挂" mindset: each case crafts a malicious input and asserts the parser
//! is BOUNDED — it returns within a wall-clock deadline (a hang FAILS the test via
//! a watchdog thread + recv_timeout) and either errors or safe-truncates, never
//! blowing up memory or writing outside the intended area.
//!
//! Fixtures: committed under `tests/fixtures/office/`, (re)generated by
//! `scripts/gen-office-fixtures.py`. The bomb fixtures are a few-KB-to-100KB on
//! disk but decompress to ~100 MB — that ratio is the whole point.
//!
//! SECURITY GUARD UNDER TEST: `parser.rs::read_zip_entry_string_bounded` +
//! `MAX_ZIP_ENTRY_BYTES` (64 MB per-entry / cumulative decompression cap) added
//! alongside this suite. The bomb cases below are the regression locks for that
//! guard (they REJECT the >64 MB bombs). Path-traversal + XXE/billion-laughs are
//! inert-by-construction (memory-only extraction + a non-entity-expanding XML
//! scanner) and the tests pin that.

use std::path::PathBuf;
use std::sync::mpsc;
use std::time::{Duration, Instant};

use attune_core::parser::parse_bytes;

fn office_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/office")
}

fn fixture(name: &str) -> Vec<u8> {
    let p = office_dir().join(name);
    std::fs::read(&p).unwrap_or_else(|e| {
        panic!(
            "missing office fixture {} at {} ({e}); run `python3 scripts/gen-office-fixtures.py`",
            name,
            p.display()
        )
    })
}

/// Run `parse_bytes(data, filename)` on a watchdog thread; FAIL if it does not
/// return within `deadline` (a hang / unbounded loop must not pass as "bounded").
/// Returns the parser's `Result` (Ok or Err — both are "bounded", the test
/// decides which it expects).
fn parse_with_timeout(
    data: Vec<u8>,
    filename: &'static str,
    deadline: Duration,
) -> Result<(String, String), String> {
    let (tx, rx) = mpsc::channel();
    let t0 = Instant::now();
    let handle = std::thread::Builder::new()
        .name(format!("parse-{filename}"))
        // Generous stack: a recursive/entity-expanding parser would blow this;
        // attune's scanners are iterative so this is comfortable headroom.
        .stack_size(8 * 1024 * 1024)
        .spawn(move || {
            let r = parse_bytes(&data, filename).map_err(|e| e.to_string());
            let _ = tx.send(r);
        })
        .expect("spawn watchdog thread");

    match rx.recv_timeout(deadline) {
        Ok(result) => {
            let _ = handle.join();
            let elapsed = t0.elapsed();
            assert!(
                elapsed < deadline,
                "{filename} parse returned but took {elapsed:?} (>= deadline {deadline:?})"
            );
            result
        }
        Err(mpsc::RecvTimeoutError::Timeout) => {
            // The worker is still running — a HANG. We cannot kill it, but the
            // test must fail. (The process will exit at test-binary teardown.)
            panic!(
                "SECURITY: {filename} parse HUNG past {deadline:?} — not bounded (possible \
                 decompression bomb / infinite expansion / pathological loop)"
            );
        }
        Err(mpsc::RecvTimeoutError::Disconnected) => {
            panic!("{filename} watchdog thread died without sending a result")
        }
    }
}

// A wall-clock that is comfortably above a legitimate parse of a tiny file but
// far below "OOM-then-swap-death". A bounded reject of a 100 MB-decompressed
// entry completes in well under a second on dev hardware.
const DEADLINE: Duration = Duration::from_secs(20);

// ── 1. ZIP-BOMB (high decompression ratio) ──────────────────────────────────

/// docx zip-bomb: word/document.xml is a few-KB deflate that inflates to
/// ~100 MB. With the `MAX_ZIP_ENTRY_BYTES` guard the parser must REJECT it
/// (Err) rather than allocate ~100 MB — and must return within the deadline.
#[test]
fn docx_zip_bomb_rejected_bounded() {
    let res = parse_with_timeout(fixture("bomb.docx"), "bomb.docx", DEADLINE);
    let err = res.expect_err(
        "docx zip-bomb must be REJECTED by the decompression-size guard, not parsed \
         (a ~100 MB inflate is the DoS). If this is Ok, the MAX_ZIP_ENTRY_BYTES guard \
         in parser.rs regressed.",
    );
    assert!(
        err.contains("zip bomb") || err.contains("exceeds") || err.contains("decompressed"),
        "rejection error should name the decompression bound: {err}"
    );
}

/// xlsx zip-bomb: sheet1.xml inline-string inflates to ~100 MB. The pre-scan of
/// declared uncompressed entry sizes (before calamine materializes the sheet)
/// must REJECT it bounded.
#[test]
fn xlsx_zip_bomb_rejected_bounded() {
    let res = parse_with_timeout(fixture("bomb.xlsx"), "bomb.xlsx", DEADLINE);
    let err = res.expect_err(
        "xlsx zip-bomb must be REJECTED by the pre-calamine entry-size scan, not handed \
         to calamine which would materialize ~100 MB. If Ok, the xlsx bomb guard regressed.",
    );
    assert!(
        err.contains("zip bomb") || err.contains("exceeds") || err.contains("decompressed"),
        "rejection error should name the decompression bound: {err}"
    );
}

/// FLAG (BUG-3b, WARNING/security, #[ignore] follow-up): the xlsx bomb guard
/// (`parser.rs::xlsx_bytes_to_text` pre-scan) trusts `ZipFile::size()`, which
/// `zip` reads verbatim from the central-directory `uncompressed_size`
/// (zip-2.4.2 read.rs:1733) — an ATTACKER-CONTROLLABLE field. A crafted xlsx can
/// declare a small `size()` (passing the scan) while its deflate stream inflates
/// to GB; calamine then accumulates the real bytes (it has no internal byte cap),
/// re-opening the OOM hole for xlsx specifically. The honest bomb (truthful
/// central dir, exercised by `xlsx_zip_bomb_rejected_bounded`) IS caught — most
/// bomb tooling writes a truthful central directory — so the guard has real
/// value; this is the residual spoofed-size hole.
///
/// docx/epub/pptx are NOT affected: they bound via `Read::take(MAX)` on the
/// ACTUAL decompressed stream (unspoofable).
///
/// Recommended fix (larger, hence follow-up not inline): for xlsx, do a real
/// bounded decompression of each workbook part calamine will read (the
/// `take(MAX_ZIP_ENTRY_BYTES)` idiom from `read_zip_entry_string_bounded`) before
/// handing the workbook to calamine, or switch to an xlsx reader that caps
/// in-memory string accumulation. This test is #[ignore] until that lands; it
/// crafts a spoofed-size bomb and documents that the current declared-size scan
/// does NOT reject it (so when the real fix lands, flip the assertion to
/// `expect_err` and drop the ignore).
#[test]
#[ignore = "FLAG BUG-3b: xlsx declared-size scan is spoofable; real-decompress bound is a follow-up"]
fn xlsx_spoofed_size_bomb_not_yet_bounded() {
    // We can't easily forge a central-directory lie with stdlib zip from Rust here
    // without a custom writer; this test documents the gap and stays #[ignore] as
    // an executable note. If/when the real-decompress xlsx bound lands, replace
    // this body with a forged-size fixture + `expect_err`.
    // Intentionally trivial so it compiles and the FLAG is greppable in CI listings.
    let _ = office_dir();
}

// ── 2. ZIP-ENTRY PATH TRAVERSAL ─────────────────────────────────────────────

/// A docx that also contains an entry literally named
/// `../../../../tmp/attune_evil_marker` (and a `..\..\..` Windows variant). The
/// parser extracts `word/document.xml` to MEMORY and never iterates/writes other
/// entries to disk, so there must be no filesystem escape. We assert:
///   (a) parse succeeds + returns the benign body (the traversal entry is inert),
///   (b) NO file appears at the traversal target on disk.
#[test]
fn docx_zip_entry_path_traversal_no_fs_escape() {
    // Pre-clean the would-be escape targets so a stale file can't false-pass.
    let escape_unix = std::path::Path::new("/tmp/attune_evil_marker");
    let _ = std::fs::remove_file(escape_unix);

    let res = parse_with_timeout(fixture("traversal.docx"), "traversal.docx", DEADLINE);
    let (_title, content) = res.expect("traversal docx must parse the benign body, not error");
    assert!(
        content.contains("ATTUNE_TRAVERSAL_BODY"),
        "benign body must be extracted from word/document.xml: {content:?}"
    );
    // The malicious entry name must NEVER materialize a file outside the archive.
    assert!(
        !escape_unix.exists(),
        "SECURITY: zip-entry path traversal wrote a file to {} — parser must extract to \
         memory only, never honor entry names as filesystem paths",
        escape_unix.display()
    );
    // The PWNED payload must not leak into indexed content either.
    assert!(
        !content.contains("PWNED_TRAVERSAL"),
        "traversal payload entry leaked into extracted content: {content:?}"
    );
}

// ── 3. BILLION-LAUGHS / XXE in word/document.xml ────────────────────────────

/// docx whose word/document.xml carries a billion-laughs DTD entity bomb
/// (`&lol9;` would expand to ~3 GB if expanded) plus an external-entity
/// `<!ENTITY xxe SYSTEM "file:///etc/passwd">`. attune's `strip_xml_tags` is a
/// character scanner that does NOT process DTDs / expand entities / fetch
/// external resources, so this must be inert: bounded time, no entity blowup,
/// and NO /etc/passwd content in the output.
#[test]
fn docx_billion_laughs_and_xxe_inert_bounded() {
    let res = parse_with_timeout(fixture("laughs.docx"), "laughs.docx", DEADLINE);
    let (_title, content) = res.expect("billion-laughs docx must parse bounded, not error/hang");

    // Bounded output — no 3 GB entity explosion. The body is tiny; a few KB max.
    assert!(
        content.len() < 1_000_000,
        "SECURITY: output is {} bytes — entity expansion blew up (billion-laughs not inert)",
        content.len()
    );
    // The benign literal text survives (entities left as-is / dropped, not expanded).
    assert!(
        content.contains("safe text") && content.contains("ATTUNE_LAUGHS_BODY"),
        "benign body text must survive: {content:?}"
    );
    // XXE: no external-entity fetch — /etc/passwd contents must NOT appear.
    assert!(
        !content.contains("root:") && !content.contains("/bin/bash") && !content.contains(":0:0:"),
        "SECURITY: XXE external-entity content leaked (looks like /etc/passwd): {content:?}"
    );
    // The expanded entity token (if expansion happened) would multiply 'lol'.
    // A non-expanding scanner keeps the literal `&lol9;` reference at most once.
    assert!(
        content.matches("lol").count() < 100,
        "SECURITY: 'lol' appears {} times — entity expansion occurred: {content:?}",
        content.matches("lol").count()
    );
}

// ── 4. OVERSIZED SINGLE ENTRY (genuinely large, not a ratio trick) ──────────

/// docx whose word/document.xml is a single genuinely-large (~50 MB) entry. This
/// probes an output-size bound distinct from the high-ratio bomb. 50 MB is under
/// the 64 MB cap so it is ACCEPTED today (bounded, no hang) — this pins that a
/// legitimately-large-but-under-cap doc still parses, and that the cap is what
/// separates it from the >64 MB bomb (raise the bomb above the cap → rejected).
#[test]
fn docx_big_single_entry_bounded_accepted() {
    let res = parse_with_timeout(fixture("big_entry.docx"), "big_entry.docx", DEADLINE);
    let (_title, content) = res.expect(
        "a ~50 MB single-entry docx (under the 64 MB cap) must parse bounded, not error/hang",
    );
    // It parsed; content is large but bounded by the (under-cap) entry size.
    assert!(!content.is_empty(), "big entry must yield content");
    assert!(
        content.len() <= 64 * 1024 * 1024,
        "content {} bytes must be bounded by the per-entry cap",
        content.len()
    );
}

// ── 5. GARBAGE / TRUNCATED CONTAINERS → graceful Err, never panic/hang ──────

/// Truncated or non-zip bytes with office extensions must produce a graceful
/// Err (or empty), never a panic or hang. This is the cheap-but-essential
/// "malformed upload" robustness leg.
#[test]
fn malformed_office_containers_graceful_error() {
    for name in ["junk.docx", "junk.xlsx", "junk.pptx", "junk.epub"] {
        let data = b"PK\x03\x04 truncated not-a-real-zip \x00\xff".to_vec();
        let res = parse_with_timeout(data, leak_name(name), Duration::from_secs(10));
        // Either Err (most formats) — must NOT panic/hang (the watchdog enforces that).
        // calamine/zip may also return an empty Ok for some truncations; both are
        // "bounded + safe". The hard requirement is: it returned, no panic.
        let _ = res;
    }
}

/// `parse_bytes` takes a `&'static str` filename in our timeout helper; produce a
/// leaked static for the test-only filenames above.
fn leak_name(s: &str) -> &'static str {
    Box::leak(s.to_string().into_boxed_str())
}
