//! PDF ingest integration tests over committed deterministic fixtures.
//!
//! Fixtures live in `tests/fixtures/pdf/` and are generated by the committed
//! `scripts/gen-pdf-fixtures.py` (PyMuPDF), so they are reproducible +
//! version-controlled. See `docs/TESTING.md §2.1` (PDF tier).
//!
//! Coverage:
//!   - text-en.pdf      English text layer → key English tokens survive
//!   - text-zh.pdf      Chinese text layer → key Chinese tokens survive
//!   - mixed-zhen.pdf   BOTH a Chinese token AND an English token survive
//!   - scanned.pdf      image-only (no text layer) → `needs_ocr` routes true
//!
//! The OCR *leg* itself (PP-OCR / tesseract) is env-gated elsewhere; here we
//! assert the routing DECISION deterministically (needs_ocr on raw extract),
//! which holds with zero OCR backends installed.

use attune_core::{ocr, parser};
use std::path::PathBuf;

fn fixture(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/pdf")
        .join(name)
}

fn fixture_bytes(name: &str) -> Vec<u8> {
    std::fs::read(fixture(name)).unwrap_or_else(|e| panic!("read fixture {name}: {e}"))
}

/// pdf_extract inserts spurious spaces inside Latin words based on glyph
/// positioning/kerning (e.g. "borrowing" → "bor rowing"). For token-presence
/// assertions on extracted English we compare against a whitespace-stripped
/// copy. This reflects real extraction behavior — we still assert the chars
/// survive, just not their exact intra-word spacing.
fn despace(s: &str) -> String {
    s.chars().filter(|c| !c.is_whitespace()).collect()
}

#[test]
fn text_en_pdf_extracts_english_tokens() {
    let (_title, content) = parser::parse_file(&fixture("text-en.pdf"))
        .expect("text-en.pdf should parse via text layer");
    // Known content (3 lines incl. "The quick brown fox ... Rust ownership and borrowing ...").
    // Match on a whitespace-stripped copy because pdf_extract inserts spurious
    // intra-word spaces (see despace()).
    let flat = despace(&content);
    for tok in ["quick", "brown", "fox", "Rust", "ownership", "borrowing"] {
        assert!(
            flat.contains(tok),
            "text-en.pdf extraction missing '{tok}' (despaced); got: {content:?}"
        );
    }
    // Real text layer → must NOT route to OCR.
    assert!(
        !ocr::needs_ocr(&content),
        "text-en.pdf has a real text layer; needs_ocr must be false (chars={})",
        content.chars().filter(|c| !c.is_whitespace()).count()
    );
}

#[test]
fn text_zh_pdf_extracts_chinese_tokens() {
    let (_title, content) = parser::parse_file(&fixture("text-zh.pdf"))
        .expect("text-zh.pdf should parse via text layer");
    // Known content (3 lines incl. 向量检索 / 借条 / 分词).
    for tok in ["向量", "检索", "借条"] {
        assert!(
            content.contains(tok),
            "text-zh.pdf extraction missing '{tok}'; got: {content:?}"
        );
    }
}

#[test]
fn mixed_zhen_pdf_preserves_both_languages() {
    let (_title, content) = parser::parse_file(&fixture("mixed-zhen.pdf"))
        .expect("mixed-zhen.pdf should parse via text layer");
    // Known content: "项目 Running 测试 with embedding 向量 search 检索。"
    let flat = despace(&content);
    let has_english = flat.contains("Running") || flat.contains("search") || flat.contains("embedding");
    let has_chinese = content.contains("向量") || content.contains("检索") || content.contains("测试");
    assert!(
        has_english,
        "mixed PDF lost the English token (Running/search); got: {content:?}"
    );
    assert!(
        has_chinese,
        "mixed PDF lost the Chinese token (向量/检索/测试); got: {content:?}"
    );
}

#[test]
fn scanned_pdf_routes_to_ocr() {
    // Raw pdf_extract output on the image-only PDF must be thin (< 100 chars)
    // so the parser routes to the OCR leg. This is the deterministic routing
    // decision, independent of whether an OCR backend is installed.
    let data = fixture_bytes("scanned.pdf");
    let raw = pdf_extract::extract_text_from_mem(&data)
        .expect("scanned.pdf is a valid PDF; pdf_extract should not error");
    let non_ws = raw.chars().filter(|c| !c.is_whitespace()).count();
    assert!(
        non_ws < 100,
        "scanned.pdf must have a thin text layer (<100 chars) to trigger OCR routing, got {non_ws}: {raw:?}"
    );
    assert!(
        ocr::needs_ocr(&raw),
        "scanned.pdf must route to OCR (needs_ocr == true)"
    );
}

#[test]
fn parse_bytes_path_matches_parse_file_for_text_pdf() {
    // The in-memory upload path (parse_bytes) and the disk path (parse_file)
    // must agree for a text-layer PDF — both go through pdf_extract.
    let data = fixture_bytes("text-en.pdf");
    let (_t, content) =
        parser::parse_bytes(&data, "text-en.pdf").expect("parse_bytes on text PDF");
    assert!(
        despace(&content).contains("quickbrownfox"),
        "parse_bytes lost text: {content:?}"
    );
}
